var rebindingkey;
var keycoderaw;
var rebindingkeynumber;
var localStorage;
function changecss(a, b, c){};
var keyboard_shortcuts_enabled;
var history_retention;
var history_container;
var history_id;
function clear_old_history(){};
var main_body;
function keybound_links_nontabbable(){};
var history_above;
var scrolltarget;
function scrollTo(a, b){};